# Generated by Django 3.2.25 on 2025-11-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20251103_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Траты'), ('expense', 'Доход')], max_length=7),
        ),
    ]
